config/routes.rb
Rails.application.routes.draw do

  resource :sessions, only: %i(create new destroy)
  resource :users, only: %i(create new)

  resources :products do
  	resources :reviews
  end

	root :to => 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews, dependent: :destroy
	belongs_to :user

	validates :name, :description, :price_in_cents, presence: true
	validate :price_in_cents_is_integer

	def price_in_cents_is_integer
		unless price_in_cents.class == Integer
      errors[:price_in_cents] << 'must be an integer'
    end
	end

	def price_in_dollars
	  price_in_dollars = price_in_cents.to_f / 100
	  sprintf("$%.2f", price_in_dollars)
	end

end

app/models/review.rb
class Review < ApplicationRecord

validates :user_id, uniqueness: { scope: :product_id, message: 'should only exist once per product and user' }

	belongs_to :product

	has_one :user

	# validates :name, :text, presence: true

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
	validates :email, presence: true


	has_many :products
	has_many :reviews

	def current_user
	  session [:user_id] && User.find(session[:user_id])
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user


	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def load_product
		@product = Product.find(params[:id])
	end

	def load_review
		@review = Review.find_by(product_id: params[:id])
	end

	def ensure_logged_in
		unless current_user
			flash[:alert] = "Please log in"
			redirect_to new_sessions_url
		end
	end

	# def ensure_user_owns_product
	#   unless current_user.id == @product.user_id
	#     flash[:alert] = "Please log in"
	#     redirect_to new_sessions_url
	#   end
	# end

	# def ensure_user_owns_review
	# 	unless current_user == @review.user
	# 		flash[:alert] = "You are not authorised for that."
	# 		redirect_to new_sessions_url
	# 	end
	# end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :ensure_logged_in, except: [:show, :index]
before_action :load_product, only: [:show, :edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new
		@product.assign_attributes({
			name: params[:product][:name],
			description: params[:product][:description],
			price_in_cents: params[:product][:price_in_cents],
			pic_url: params[:product][:pic_url],
			user_id: current_user.id
		})
		if @product.save
			redirect_to product_path(@product), notice: "You have created a product!"
		else
			@product.errors
		end
	end

	def update
		if @product.update({
			name: params[:product][:name],
			description: params[:product][:description],
			price_in_cents: params[:product][:price_in_cents],
			pic_url: params[:product][:pic_url],
			user_id: current_user.id
		})
			redirect_to root_url
		else
			flash[:alert] = @product.errors
			render :edit
		end
	end

	def show
		@review = Review.new
	end

	def edit

	end

	def destroy
		@product.destroy
		redirect_to root_url, notice: "Destruction successful!"
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :ensure_logged_in, except: [:show, :index]
before_action :load_review, only: [:new, :show, :destroy]

	def index
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@review = Review.new
	end

	def edit
		@review = Review.find_by(product_id: params[:product_id], user_id: current_user.id)
		@product = Product.find(params[:product_id])
	end

	def create
		@review = Review.new
		@review.assign_attributes({
			name: params[:review][:name],
			text: params[:review][:text],
			product_id: params[:product_id],
			user_id: current_user.id })

			if @review.save
				redirect_to product_path(params[:product_id])
				flash[:notice] = "Review successfully created"
			else
				flash[:notice] = "Nothing happened."
			end
	end

	def update
		@review = Review.find_by(product_id: params[:product_id], user_id: current_user.id)
		@review.assign_attributes(
			name: params[:review][:name],
			text: params[:review][:text],
			product_id: params[:product_id],
			user_id: current_user.id )

		if @review.save
			redirect_to product_path(params[:product_id])
			flash[:notice] = "Review successfully updated"
		else
			flash[:notice] = "Nothing happened."
		end
	end

		def destroy
			@review.destroy
			redirect_to root_url, notice: "Destruction successful!"
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

#  LOG IN METHOD HERE
  def create
    u = User.find_by(email: params[:session][:email])

    if u && u.authenticate(params[:session][:password])
      flash[:notice] = 'Login successful'

      session[:user_id] = u.id

      redirect_to root_url
    else
      flash[:error] = 'Access DENIED!'
      render :new
    end
  end

# LOG OUT METHOD HERE
  def destroy
    flash[:notice] = 'Logged out successfully'
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.email = params[:user][:email]
    @user.password = params[:user][:password]

    if @user.save
      flash[:notice] = 'User successfully created!'
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash[:alert] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav>
  <%= link_to "Create new product?", new_product_path %> | <%= link_to "Go Back", root_path %>
  <% if session[:user_id] %>
    <p>
      <%= link_to 'Home', root_path %>
      |
      <%= link_to 'Log Out', sessions_path, method: :delete %>
    </p>

    Hello User#<%= session[:user_id] %><br>
    <% else %>
    <p>
      <%= link_to 'New User', new_users_path %> | <%= link_to 'Login', new_sessions_path %>
    </p>
  <% end %>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>
</nav>

  <body>

    <%= yield %>



  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br>

	<%= f.label :description %>
	<%= f.text_field :description %><br>

	<%= f.label :price_in_cents %>
	<%= f.number_field :price_in_cents %><br>

	<%= f.label :pic_url %>
	<%= f.text_field :pic_url %><br>

	<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h2>EDIT PRODUCT</h2>

<%= render 'form' %>

app/views/products/index.html.erb
<h2>DISPLAY ALL PICTURES</h2>
<% @products.each do |product| %>
	<div>
		<div class="picture">
			<%= link_to product_path(product) do %>
	  		<%= image_tag(product.pic_url, class: "picture") %>
			<% end %>
			</div>
		<div class=""><%= product.name %></div>
		<div class=""><%= product.description %></div>
		<div class=""><%= product.price_in_dollars %></div>
		<br>
	</div>

<% end %>

app/views/products/new.html.erb
<h2>ADD NEW PRODUCT</h2>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="">
	<h2>SHOW PRODUCT</h2>
		<%= image_tag @product.pic_url %>
		<%= @product.name %><br>
		<%= @product.price_in_cents %><br>
		<%= @product.description %>
		<%= link_to "Update this product?", edit_product_path(@product) %>
		<%= link_to 'Delete this product?',  product_path(@product), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<div class="show_all_reviews">
	<h2>ALL REVIEWS</h2>
	<% @product.reviews.each do |r| %>
								<%= r.text %>
		<p>Reviewer: <%= r.name %></p>
		<p>Created at: <%= r.created_at %></p>

		<%= link_to "Update this review?", edit_product_review_path(@product, r) %>
		<%= link_to "Delete this review?", product_review_path(@product, r), method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
</div>

<div class="create_reviews">
	<p>Write a review:</p>
	<%= form_for [@product, @review] do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br>

		<%= f.label :text %>
		<%= f.text_field :text %><br>

		<%= f.submit %>
	<% end %>
</div>

app/views/reviews/create.html.erb
<h2>reviews/new</h2>

<div class="create_reviews">
	<p>Write a review:</p>
	<%= form_for [@product, @review] do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %><br>

		<%= f.label :text %>
		<%= f.text_field :text %><br>

		<%= f.submit %>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= form_for @review, url: product_review_path(@product, @review) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br>

	<%= f.label :text %>
	<%= f.text_field :text %><br>

	<%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1>Showing Review Here</h1>

app/views/users/new.html.erb
<% if @user.errors.any? %>
 <ul>
	<% @user.errors.full_messages.each do |message| %>
	 <li><%= message %></li>
	<% end %>
 </ul>
<% end %>

<h1>Sign Up</h1>

	<%= form_for @user do |f| %>

 <div class='field'>
		<%= f.label :email %>
		<%= f.email_field :email %>
 </div>

  <div class='field'>
		<%= f.label :password %>
		<%= f.password_field :password %>
 </div>

		<%= f.submit 'Sign Up '%>

	<% end %>